{% set version = "5.3" %}

package:
    name: qrcode
    version: {{ version }}

source:
    fn: qrcode-{{ version }}.tar.gz
    url: https://pypi.io/packages/source/q/qrcode/qrcode-{{ version }}.tar.gz
    md5: af41b650a3675d0a0366f842de9786b9

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record record.txt
    entry_points:
        - qr = qrcode.console_scripts:main

requirements:
    build:
        - python
        - setuptools
        - six
    run:
        - python
        - six
        - colorama

test:
    imports:
        - qrcode
        - qrcode.image
        - qrcode.tests
    commands:
        - qr --help

about:
    home: https://github.com/lincolnloop/python-qrcode
    license: BSD-3-Clause
    summary: QR Code image generator

extra:
    recipe-maintainers:
        - ocefpaf
