{% set name = "qrcode" %}
{% set version = "8.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 35c3f2a4172b33136ab9f6b3ef1c00260dd2f66f858f24d88418a015f446506c

build:
  number: 0
  entry_points:
    - qr = qrcode.console_scripts:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  skip: true  # [py<39]

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - colorama  # [win]
  run_constrained:
    - pillow >=9.1.0

test:
  imports:
    - qrcode
    - qrcode.base
    - qrcode.compat.etree
    - qrcode.compat.png
    - qrcode.console_scripts
    - qrcode.constants
    - qrcode.exceptions
    - qrcode.image
    - qrcode.image.base
    - qrcode.image.pure
    - qrcode.image.styles
    - qrcode.main
    - qrcode.release
    - qrcode.util
  commands:
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    # ValueError: Invalid format string
    - set PYTHONUTF8=1              # [win]
    - set PYTHONIOENCODING="UTF-8"  # [win]
    - pytest --pyargs qrcode.tests
    - qr --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/lincolnloop/python-qrcode
  summary: QR Code image generator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: A Quick Response code is a two-dimensional pictographic code used for its fast readability and comparatively large storage capacity. The code consists of black modules arranged in a square pattern on a white background.
  dev_url: https://github.com/lincolnloop/python-qrcode
  doc_url: https://github.com/lincolnloop/python-qrcode/blob/main/README.rst

extra:
  recipe-maintainers:
    - ocefpaf