{% set name = "qrcode" %}
{% set version = "7.4.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/qrcode-{{ version }}.tar.gz
  sha256: 9dd969454827e127dbd93696b20747239e6d540e082937c90f14ac95b30f5845

build:
  number: 0
  entry_points:
    - qr = qrcode.console_scripts:main
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python
    - colorama # [win]
    - typing-extensions
    - pypng

test:
  imports:
    - qrcode
    - qrcode.image
  commands:
    - pip check
    - qr --help
  requires:
    - pip

about:
  home: https://github.com/lincolnloop/python-qrcode
  summary: QR Code image generator
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  description: A Quick Response code is a two-dimensional pictographic code used for its fast readability and comparatively large storage capacity. The code consists of black modules arranged in a square pattern on a white background.
  dev_url: https://github.com/lincolnloop/python-qrcode
  doc_url: https://github.com/lincolnloop/python-qrcode/blob/main/README.rst

extra:
  recipe-maintainers:
    - ocefpaf
