travis:
  secure:
    BINSTAR_TOKEN: u+lBUsqGyxHgUN2pcDPjUmF4vB6JtgwA0PBn6dUel+JMa8wZe7l/FIfeFNzlM2fKYaICTnZ40bOoqVfSSyQTiZZ9rgQFacc4tx1KZ2JTopkERu3M3DzSfhYMKbzfZGx/T5tfJmVarcTCyzIOw+Rv3RYQyYsHZkv+UZarzRNP36HS8xDzcmhxU+PayioB8Y+u45cdjn91gInDBSG6wifyCYqZeK5uK9o5pkxAAxCu5bffAKxC1aUclLa0MEDsVcK8fhdy9TPDwdppiGhg9Y68hAg84weRj/zpA6XDCDLLBEpmfeFXN7OZREj9Jdhv2aVeyCSW086nXRB4ME7gjaGnOMBC4hJDCkaXSHbnRgqtM4YQ+QUQKi/SyeM0m5DItAJbV4tDMBZNvJDs5wwILgi7qRSyDf9ih9xMQyW+FPx4qwTjhRNjFTqq8iySfNik1xNUK+K+/FC3IP8YIM2sbQaMbvk/SdSqWyMGx2ofMbnP4jAw+lQORhR1Usp6wy/29CrdQQVYwuqSUPh1z51YuwpSioNxuym9bziJroJtbBOOp7P7ITpual3G99eMu+WCmVdGWt1Bgkl3FoEU/CSoGbD/adQ2J4aH2VIG/67pj9vbZDQnv0A/yxSQAefAvfSA0BMPDExqT2lcT86fQAIovefhVwDAdSSpNf5oUzTFaF7ipfQ=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
