travis:
  secure:
    BINSTAR_TOKEN: VfUa6hJikbtzIOupjqZPnR/pAy0M+/dCoJqiPJLpXO80mJXO0xJZaYyviSJsPj1OJZwMj3RExidiaQcTn7fTopxTsDZ43b3DzzZmr4eoQOFxZNXAzqoa/MRh+Xp8FUuuQM2vErNqXVHDqyq8cpxd2OQpOeBl70VT7sTINIDMUlM2XeBKrHiNIs2cVOCGUcJ2/1XTQCEhyc5lvYxkdCD+nYMCjZzWtiUJPr/bdovVyyZ82yvaafQK4WEJKJtjXfz11QLzRHHhJ1bVP1bfJJXPnuCixRXfoeQzQHWf/HWqo46LHf5UEiesiXzesBZTJET0jMuxZfF+IKBhzXNEmfUuqU9jtqlHzSywsFTgcfEEFd6BrytHWAuo0jLrBLIwT3c7tHxAL1A0MIA07/FYuPG2uG2MLBL2JF01A0jUzPSxG/DclpE3NPFSpvxvMlcnwXF5kpqCQLosAN1MmtZJaI4sW7GRcOjlzxFFEeuxx75t0KIUE9w/jWrGrjDZzzcLk3CQplJ4g5zXanPhDZQRVDzyYO7UdETp/aWdx0y350ILI4cRdHOxFzjOmC3EXrQOzcxhu2d1P6hW/+Eyit2cR/wqc4jXbhxcl2k4izbQJ8aJiwxqjv+gYYJCJqoPT9gyFK006kPguTXapvvCvX0yriskOvTHsaLchEEIhl87uuCPn/k=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
