travis:
  secure:
    BINSTAR_TOKEN: 1IS63nwQJSiMoNjzxPODjXLwmQSz6ngZ9JvOm0hSunQ/XDiAEfCvJTlq7hMb5V9xrvDod4tZZDoWyhmY07IG+2uSsJAxmIniBbC46Fvn1GfqzmyAjYFiNrkeB2jMOQ7mdlUeYAeDLoBh4GQbBHA7dYgRyuKe7ShRTsa5OCXiH9FrTvfsoaQbHz34vUH14ILmeEAPKeR4dBaev8VG6hH7EVOOjkqAteKleLIogwBIpnlJDb4Mb0Qh0SJL0lvw/103Adbsb6kcD/XdgG5briFyeT4aHHfyom9NvDtQqheedBQTEqky87/DWu1GOmml4onh8bUnP6NfI3fYJIkGNv7+gtQCCZdhhe7D402+YbjP++/fK9uwmvmMaohZrTOs6hCiBIhaHjCaNX5K7jzv8K1mGgHCEhG49hlYxOIIiDuLoX7FQUkLH/R6XXuIdh6jP62T4/1SnwKZY53AX/CpBrpbwC4FeJNzwzvQRQTkQYH0Fo6EVETpRbxC87fRNkS2B8QYTWUghooOiMKMYZocYpJarhAH2ro8XD8OYWjypWZSx+S4jXD9UJWHmc/SfJrKJwP68fV766HmjjiVGuYGG9UIEfmoK9J9mEWx+SQWyJg2vw1Zf9d0Bi8FRtr0s/GCmeN5YhjnMJshc+b7fDY8jKMRyrWhbGGDIeYL7oWH2KeAqj0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
